---
title: "internal.fajfer.org"
subtitle: "Homer Dashboard"
logo: "logo.png"
header: true
footer: '<p><a href="https://github.com/bastienwirtz/homer">Homer</a></p>'
theme: default
colors:
  light:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#f5f5f5"
    card-background: "#ffffff"
    text: "#363636"
    text-header: "#ffffff"
    text-title: "#303030"
    text-subtitle: "#424242"
    card-shadow: rgba(0, 0, 0, 0.1)
    link: "#3273dc"
    link-hover: "#363636"
  dark:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#131313"
    card-background: "#2b2b2b"
    text: "#eaeaea"
    text-header: "#ffffff"
    text-title: "#fafafa"
    text-subtitle: "#f5f5f5"
    card-shadow: rgba(0, 0, 0, 0.4)
    link: "#3273dc"
    link-hover: "#ffdd57"
message:
  style: "is-info"
  title: "Hej!"
  icon: "fa fa-info-circle"
  content: "Patrzysz na dashboard do odszukiwania adresów do części usług jakie mam. Wiem, że jest wystawiony publicznie mimo, że nazywa się internal."
links:
  - name: "GitHub"
    icon: "fab fa-github"
    url: "https://github.com/fajfer"
    target: "_blank"
  - name: "Mastodon"
    icon: "fab fa-mastodon"
    url: "https://mastodon.social/@fajfer"
    target: "_blank"
services:
  - name: "Usługi reszka.org"
    icon: "fab fa-linux"
    items:
      - name: "PeerTube"
        icon: "fab fa-youtube"
        subtitle: "Peertube (odpowiednik YouTube)"
        url: "https://tube.reszka.org"
      - name: "Synapse"
        icon: "fas fa-comments"
        subtitle: "Serwer Matrix (homeserver)"
        url: "https://reszka.org"
      - name: "Vikunja"
        icon: "fa fa-user-plus"
        subtitle: "Task manager/issue tracker"
        url: "https://zadania.reszka.org"
      - name: "Radicale"
        icon: "fas fa-calendar-alt"
        subtitle: "Serwer CalDAV/CardDAV"
        url: "https://kalendarz.reszka.org"

  - name: "Usługi zewnętrzne"
    icon: "fas fa-globe"
    items:
      - name: "blog.fajfer.org"
        icon: "fas fa-blog"
        subtitle: "Mój blog"
        url: "https://blog.fajfer.org"
      - name: "Mumble"
        icon: "fas fa-comments"
        subtitle: "Serwer Mumble"
        url: "https://fajfer.org"
      - name: "Homer"
        icon: "fas fa-home"
        subtitle: "Ten dashboard"
        tag: "infra"

  - name: "Usługi wewnętrzne"
    icon: "fas fa-server"
    items:
      - name: "Jellyfin"
        icon: "fas fa-film"
        subtitle: "Serwer strumieniowania multimediów"
        tag: "media"
        url: "https://jellyfin.internal.fajfer.org"
      - name: "Deluge"
        icon: "fas fa-cloud-download-alt"
        subtitle: "Klient torrentów"
        tag: "media"
        url: "https://deluge.internal.fajfer.org"
      - name: "Soulseekd (slskd)"
        icon: "fas fa-music"
        subtitle: "Daemon Soulseek"
        tag: "media"
        url: "https://slskd.internal.fajfer.org"
      - name: "ArgoCD"
        icon: "fas fa-code-branch"
        subtitle: "Platforma GitOps CD"
        tag: "infra"
        url: "https://argocd.internal.fajfer.org"
